name: adhoc_plugin
description: Flutter plugin that allows creating and managing a mobile (Android only) ad hoc network
version: 1.0.0
author: Thai Dinh Le <Thai.Dinh.Le.pro@gmail.com>
homepage: https://github.com/thai-dinh/adhoc_plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  cryptography: ^2.0.1
  flutter_reactive_ble: ^3.1.1+1
  json_annotation: ^4.0.1
  ninja_prime: ^2.0.0
  pointycastle: ^3.0.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  mockito: ^5.0.9

flutter:
  plugin:
    platforms:
      android:
        package: com.montefiore.thaidinhle.adhoc_plugin
        pluginClass: AdhocPlugin
